login: &login
  access_key_id: <%= ENV['S3_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET'] %>

development:
  bucket_name: livingsky_development
  <<: *login
  distribution_domain: s3.amazonaws.com/livingsky_development

test:
  bucket_name: livingsky_test
  <<: *login
  distribution_domain: s3.amazonaws.com/livingsky_test

production:
  bucket_name: livingsky_production
  <<: *login
  distribution_domain: s3.amazonaws.com/livingsky_production
